spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/bookmyshow
spring.datasource.username=bookuser
spring.datasource.password=bookpass
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
